#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=50gb,walltime=4:00:00
#PBS -N pRF
#PBS -V

fsdir=$(jq -r .output config.json)
prf_surfs=$(jq -r .prf_surfs config.json)

export SUBJECTS_DIR=`pwd`
cp -R $fsdir $SUBJECTS_DIR && cp -R $fsdir $SUBJECTS_DIR/$(basename $fsdir)_MNI
chmod -R +rw $SUBJECTS_DIR/$(basename $fsdir)_MNI
chmod -R +rw $SUBJECTS_DIR/$(basename $fsdir)

rm -R $SUBJECTS_DIR/$(basename $fsdir)_MNI/surf && mkdir $SUBJECTS_DIR/$(basename $fsdir)_MNI/surf



mkdir interpolated_prf_surfs
mkdir -p prf/prf_surfaces varea varea_surf

time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main

mkdir ret_output

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://davhunt/neuropythy:1.5.1 bash -c "python ./interpolate.py \
  && python -m neuropythy register_retinotopy output \
  --verbose \
  --lh-eccen=interpolated_prf_surfs/lh.eccentricity \
  --lh-angle=interpolated_prf_surfs/lh.polarAngle \
  --lh-weight=interpolated_prf_surfs/lh.r2 \
  --lh-radius=interpolated_prf_surfs/lh.rfWidth \
  --rh-eccen=interpolated_prf_surfs/rh.eccentricity \
  --rh-angle=interpolated_prf_surfs/rh.polarAngle \
  --rh-weight=interpolated_prf_surfs/rh.r2 \
  --rh-radius=interpolated_prf_surfs/rh.rfWidth \
  --subjects-dir=`pwd` \
  && cp -R ./$(basename $fsdir) ./ret_output \
  && ./create_vtks.sh ./ret_output/$(basename $fsdir)"

time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main #create GIFTI-format surfaces too

cp prf/prf_surfaces/lh.varea.gii varea_surf/lh.parc.annot.gii
cp prf/prf_surfaces/rh.varea.gii varea_surf/rh.parc.annot.gii

rm ./prf/prf_surfs.mat
rm -rf ./ret_output
