#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=50gb,walltime=2:00:00
#PBS -N pRF
#PBS -V

cd /N/u/davhunt/Carbonate/Downloads/app-bayesian-retinotopy
fsdir=$(jq -r .output config.json)
prf_surfs=$(jq -r .prf_surfs config.json)
surfaces=$(jq -r .surfaces config.json)

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./convert_vtk2gii.sh ${surfaces} ${prf_surfs}

export SUBJECTS_DIR=`pwd`
cp -R $fsdir $(basename $fsdir) && cp -R $fsdir $(basename $fsdir)_prf_space
chmod -R +rw $(basename $fsdir) $(basename $fsdir)_prf_space
rm -R $SUBJECTS_DIR/$(basename $fsdir)_prf_space/surf && mkdir $SUBJECTS_DIR/$(basename $fsdir)_prf_space/surf

mkdir interpolated_prf_surfs
mkdir -p prf/prf_surfaces varea varea_surf
cp key.txt label.json varea && cp key.txt label.json varea_surf

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://davhunt/neuropythy:1.5.1 bash -c "python ./interpolate.py \
  && python -m neuropythy register_retinotopy $(basename $fsdir) \
  --verbose \
  --lh-eccen=interpolated_prf_surfs/lh.eccentricity \
  --lh-angle=interpolated_prf_surfs/lh.polarAngle \
  --lh-weight=interpolated_prf_surfs/lh.r2 \
  --lh-radius=interpolated_prf_surfs/lh.rfWidth \
  --rh-eccen=interpolated_prf_surfs/rh.eccentricity \
  --rh-angle=interpolated_prf_surfs/rh.polarAngle \
  --rh-weight=interpolated_prf_surfs/rh.r2 \
  --rh-radius=interpolated_prf_surfs/rh.rfWidth \
  --subjects-dir=`pwd`"

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./create_vtks.sh $(basename $fsdir)

time singularity exec -e docker://brainlife/dipy:0.16.0 bash -c "./create_R2.py && ./convert_curv2gii.py"

if [ ! -s ./prf/prf_surfaces/lh.polarAngle.gii ];
then
	echo "output missing"
	exit 1
fi

#rm -rf output output_prf_space interpolated_prf_surfs
